export const data = [
    {
        tutor: "Olivia Moore",
        title: "Mobile App Development with Flutter",
        modules: 11,
        likes: 250,
        category: "app-development",
        reviews: 36,
        duration_hours: 45,
        students_enrolled: 1300,
        img_url: "https://source.unsplash.com/man-using-laptop-VzJjPuk53sk",
    },
    {
        tutor: "John Smith",
        title: "Web Development 101",
        modules: 12,
        likes: 248,
        category: "web-development",
        reviews: 35,
        duration_hours: 30,
        students_enrolled: 1200,
        img_url:
            "https://source.unsplash.com/person-using-black-laptop-computer-jKL2PvKN8Q0",
    },

    {
        tutor: "David Wilson",
        title: "Ui/Ux Design",
        modules: 7,
        likes: 112,
        category: "ui-ux",
        reviews: 18,
        duration_hours: 12,
        students_enrolled: 550,
        img_url:
            "https://source.unsplash.com/a-neon-sign-is-lit-up-in-the-dark-PapkdyVWXlU",
    },

    {
        tutor: "John Smith",
        title: "Product Management",
        modules: 12,
        likes: 248,
        category: "product-management",
        reviews: 35,
        duration_hours: 30,
        students_enrolled: 1200,
        img_url:
            "https://source.unsplash.com/person-using-black-laptop-computer-jKL2PvKN8Q0",
    },

    {
        tutor: "Emily Davis",
        title: "Data Science Fundamentals",
        modules: 10,
        likes: 312,
        category: "technical-writting",
        reviews: 42,
        duration_hours: 40,
        students_enrolled: 1500,
        img_url:
            "https://source.unsplash.com/man-in-black-long-sleeve-shirt-using-computer-_Fx34KeqIEw",
    },
    {
        tutor: "Michael Johnson",
        title: "Digital Marketing Masterclass",
        modules: 8,
        likes: 198,
        category: "cyber-security",
        reviews: 28,
        duration_hours: 20,
        students_enrolled: 800,
        img_url:
            "https://source.unsplash.com/a-woman-sitting-at-a-table-using-a-laptop-computer-m2lu-XzB8as",
    },
    {
        tutor: "Sarah Miller",
        title: "Photography Basics",
        modules: 6,
        likes: 132,
        category: "cyber-security",
        reviews: 20,
        duration_hours: 15,
        students_enrolled: 600,
        img_url:
            "https://source.unsplash.com/black-dslr-camera-floating-over-mans-hand-at-the-woods-WxM465oM4j4",
    },
    {
        tutor: "Alice Brown",
        title: "Artificial Intelligence for Beginners",
        modules: 15,
        likes: 420,
        category: "app-development",
        reviews: 55,
        duration_hours: 50,
        students_enrolled: 1800,
        img_url:
            "https://source.unsplash.com/man-in-black-and-gray-suit-action-figure-naSAHDWRNbQ",
    },
    {
        tutor: "David Wilson",
        title: "Spanish Language Crash Course",
        modules: 7,
        likes: 112,
        category: "product-management",
        reviews: 18,
        duration_hours: 12,
        students_enrolled: 550,
        img_url:
            "https://source.unsplash.com/a-neon-sign-is-lit-up-in-the-dark-PapkdyVWXlU",
    },

    {
        tutor: "Olivia Moore",
        title: "Mobile App Development with Flutter",
        modules: 11,
        likes: 250,
        category: "app-development",
        reviews: 36,
        duration_hours: 45,
        students_enrolled: 1300,
        img_url: "https://source.unsplash.com/man-using-laptop-VzJjPuk53sk",
    },
    {
        tutor: "John Smith",
        title: "Web Development 101",
        modules: 12,
        likes: 248,
        category: "web-development",
        reviews: 35,
        duration_hours: 30,
        students_enrolled: 1200,
        img_url:
            "https://source.unsplash.com/person-using-black-laptop-computer-jKL2PvKN8Q0",
    },

    {
        tutor: "David Wilson",
        title: "Ui/Ux Design",
        modules: 7,
        likes: 112,
        category: "ui-ux",
        reviews: 18,
        duration_hours: 12,
        students_enrolled: 550,
        img_url:
            "https://source.unsplash.com/a-neon-sign-is-lit-up-in-the-dark-PapkdyVWXlU",
    },

    {
        tutor: "John Smith",
        title: "Product Management",
        modules: 12,
        likes: 248,
        category: "product-management",
        reviews: 35,
        duration_hours: 30,
        students_enrolled: 1200,
        img_url:
            "https://source.unsplash.com/person-using-black-laptop-computer-jKL2PvKN8Q0",
    },

    {
        tutor: "Emily Davis",
        title: "Data Science Fundamentals",
        modules: 10,
        likes: 312,
        category: "technical-writting",
        reviews: 42,
        duration_hours: 40,
        students_enrolled: 1500,
        img_url:
            "https://source.unsplash.com/man-in-black-long-sleeve-shirt-using-computer-_Fx34KeqIEw",
    },
    {
        tutor: "Michael Johnson",
        title: "Digital Marketing Masterclass",
        modules: 8,
        likes: 198,
        category: "cyber-security",
        reviews: 28,
        duration_hours: 20,
        students_enrolled: 800,
        img_url:
            "https://source.unsplash.com/a-woman-sitting-at-a-table-using-a-laptop-computer-m2lu-XzB8as",
    },
    {
        tutor: "Sarah Miller",
        title: "Photography Basics",
        modules: 6,
        likes: 132,
        category: "cyber-security",
        reviews: 20,
        duration_hours: 15,
        students_enrolled: 600,
        img_url:
            "https://source.unsplash.com/black-dslr-camera-floating-over-mans-hand-at-the-woods-WxM465oM4j4",
    },
    {
        tutor: "Alice Brown",
        title: "Artificial Intelligence for Beginners",
        modules: 15,
        likes: 420,
        category: "app-development",
        reviews: 55,
        duration_hours: 50,
        students_enrolled: 1800,
        img_url:
            "https://source.unsplash.com/man-in-black-and-gray-suit-action-figure-naSAHDWRNbQ",
    },
    {
        tutor: "David Wilson",
        title: "Spanish Language Crash Course",
        modules: 7,
        likes: 112,
        category: "product-management",
        reviews: 18,
        duration_hours: 12,
        students_enrolled: 550,
        img_url:
            "https://source.unsplash.com/a-neon-sign-is-lit-up-in-the-dark-PapkdyVWXlU",
    },
];
